userdata:
    Name: Sarah Wilson
    email: hackfesttrials@gmail.com
    phone: +91 9928410698
    address: bengaluru,india
    position: SDE1 google.inc

Model:
    llm: GoogleGenAI
    embeddings: GoogleGenAI
    